FROM python:3.8

COPY requirements.txt /app/requirements.txt

RUN pip install -r /app/requirements.txt

COPY templates /app/templates

COPY restserver.py /app/restserver.py

WORKDIR /app

ENTRYPOINT [ "python3", "-u", "restserver.py" ]