apiVersion: v1
kind: Service
metadata:
  name: recentcves-svc
  labels:
    app: recentcves
spec:
  ports:
    - name: recentcves
      protocol: "TCP"
      port: 5000
      targetPort: 5000
  selector:
    app: recentcves
  type: NodePort