apiVersion: v1
kind: Service
metadata:
  name: user-management-svc
  labels:
    app: user-management
spec:
  ports:
    - name: user-management
      protocol: "TCP"
      port: 5000
      targetPort: 5000
  selector:
    app: user-management
  type: NodePort